wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    code_path: code/main.py
    framework: huggingface
    huggingface_version: 4.10.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1654791264
    t:
      1:
      - 1
      - 3
      - 11
      3:
      - 16
      4: 3.8.10
      5: 0.12.2
      6: 4.10.2
      8:
      - 5
batch_size:
  desc: null
  value: 64
data_dir:
  desc: null
  value: data/
debug:
  desc: null
  value: false
device:
  desc: null
  value: cuda:0
epochs:
  desc: null
  value: 300
img_size:
  desc: null
  value: 128
inference:
  desc: null
  value: false
log_every_n_epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.0001
lr_scheduler:
  desc: null
  value: none
num_workers:
  desc: null
  value: 0
one_batch:
  desc: null
  value: false
opt:
  desc: null
  value: adam
output_dir:
  desc: null
  value: output
persistent_workers:
  desc: null
  value: false
resume:
  desc: null
  value: ''
run_name:
  desc: null
  value: ''
seed:
  desc: null
  value: 42
test_every_n_epochs:
  desc: null
  value: 15
